name: parkomat
description: A beautiful app for your parkomat.

version: 1.7.1

environment:
  sdk: ">=2.7.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  connectivity: 0.4.8+1
  connectivity_wrapper: 1.0.2
  cupertino_icons: 0.1.3
  dio: 3.0.8
  equatable: 1.1.0
  flushbar: 1.9.1
  flutter_bloc: 2.1.0
  flutter_cupertino_localizations: 1.0.1
  flutter_launcher_icons: 0.7.4
  flutter_whatsnew: 1.0.3
  get_it: 3.1.0
  jiffy: 2.2.0
  open_appstore: 1.0.2
  open_file: 3.0.1
  package_info: 0.4.0+13
  path_provider: 1.6.0
  pub_semver: 1.4.3
  share: 0.6.3+5
  shared_preferences: 0.5.6+1
  validators: 2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^3.2.5
  build_runner: ^1.7.3

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/parkomat.png"
  image_path_android: "assets/launcher/parkomat.png"
  adaptive_icon_background: "assets/launcher/parkomat-background.png"
  adaptive_icon_foreground: "assets/launcher/parkomat-foreground.png"

flutter:
  uses-material-design: true
  assets:
    - documentation/changelog_en.md
    - documentation/changelog_de.md

flutter_intl:
  enabled: true
