name: parkomat
description: A beautiful app for your parkomat.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.6
  flutter_bloc: 2.1.1
  equatable: 1.0.1
  flutter_launcher_icons: ^0.7.4
  validators: ^2.0.0+1
  flushbar: ^1.9.1
  flutter_offline: 0.3.0
  provider: ^3.2.0
  dio: 3.0.7
  intl: 0.16.0
  sprintf: 4.0.2
  jiffy: 2.1.2
  inject:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject

dependency_overrides:
  source_gen: 0.9.4+1
  analyzer: ^0.37.1
  intl: ^0.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^3.2.2
  build_runner: ^1.7.2
  inject_generator:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject_generator

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/parkomat.png"
  image_path_android: "assets/launcher/parkomat.png"
  adaptive_icon_background: "assets/launcher/parkomat-background.png"
  adaptive_icon_foreground: "assets/launcher/parkomat-foreground.png"

flutter:
  uses-material-design: true
